[openweathermap]
enabled = true
api_key = "file:~/.config/ntfd/openweathermap.txt"
city_id = "4671654"
notification_timeout = 10
notification_body = "Expected within the next 3 hours"
sync_frequency = 1800 # 30 minutes
display = "{{ temp_icon }} {{ temp_celsius }}°C"

