
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Color everywhere!
alias ls='ls --color=auto'
alias grep='grep --color'

# git bash prompt
GIT_PROMPT_ONLY_IN_REPO=0
GIT_PROMPT_FETCH_REMOTE_STATUS=0
source ~/.bash-git-prompt/gitprompt.sh

# nodejs
PATH=$HOME/bin:$HOME/src/node/node-v14.16.1-linux-x64/bin:$PATH

# Editor
export EDITOR="nvim"

# Git bash completion
source /usr/share/git/completion/git-completion.bash

# Command not found
source /usr/share/doc/pkgfile/command-not-found.bash

# ls
alias ls="lsd"

